
[tags.test_product]
source=[]


traits."check_hello".contains=["Hello"]
traits."check_world".contains=["World"]


#表达式
expression='''aa.data["test"].help()'''

#Info
info."version".text="No Version"
info."version".regexps=["Hello","MATCH-2"] #任意一个取得数据即可
info."version".expression='''aa.data["test"]'''